id: P009158
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ8064
  title: ལམ་རིམ་ནས་བྱུང་བའི་ཆུང་འབྲིང་གི་དམིགས་རྣམ་རྐང་གྲངས་ཙམ་དུ་སྡེབས་པའི་ཚིགས་བཅད་བརྒྱད་པ་
  author: ''
  volumes:
    e61ca13c133d44c1abd4a0744120b386:
      image_group_id: I1PD96638
      title: ''
      volume_number: 1
      total_pages: 6
      base_file: v001.txt
